# Generated by Django 2.2.5 on 2019-10-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento_reportes', '0003_auto_20191007_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordeninterna',
            name='localidad',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
