# Generated by Django 2.2.5 on 2019-10-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento_reportes', '0004_ordeninterna_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordeninterna',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
