# Generated by Django 2.2.5 on 2019-10-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento_reportes', '0007_auto_20191009_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordeninterna',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
