# Generated by Django 2.2.5 on 2019-11-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.AutoField(primary_key=True, serialize=False)),
                ('resp_pago', models.CharField(blank=True, max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=13)),
            ],
        ),
    ]
