# Generated by Django 2.1.7 on 2019-10-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenInterna',
            fields=[
                ('idOI', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
