# Generated by Django 2.1.7 on 2019-10-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdenInterna',
        ),
    ]
