# Generated by Django 2.2.5 on 2019-10-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenInterna',
            fields=[
                ('idOI', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_muestreo', models.DateField(blank=True, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50)),
                ('fechah_recibo', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('link_resultados', models.CharField(blank=True, max_length=300)),
                ('guia_envio', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(blank=True, max_length=15)),
                ('formato_ingreso_muestra', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2)),
                ('idioma_reporte', models.CharField(blank=True, choices=[('8809 ES', '8809 ES'), ('8992 EN', '8992 EN')], max_length=7)),
                ('mrl', models.CharField(blank=True, max_length=200)),
                ('fecha_eri', models.DateField(blank=True, null=True)),
                ('notif_e', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2)),
                ('fecha_lab', models.DateField(blank=True, null=True)),
                ('fecha_ei', models.DateField(blank=True, null=True)),
                ('envio_ti', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2)),
                ('cliente_cr', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2)),
                ('resp_pago', models.CharField(blank=True, max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=13)),
            ],
            options={
                'verbose_name': 'Orden Interna',
                'verbose_name_plural': 'Órdenes Internas',
            },
        ),
    ]
