# Generated by Django 2.2.5 on 2019-11-15 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=30)),
                ('unidad_min', models.CharField(default='', max_length=50)),
                ('tiempo', models.CharField(max_length=15)),
                ('acreditacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_dhl', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenInterna',
            fields=[
                ('idOI', models.AutoField(primary_key=True, serialize=False)),
                ('localidad', models.CharField(blank=True, max_length=50)),
                ('fecha_recepcion_m', models.DateField(blank=True, null=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_llegada_lab', models.DateField(blank=True, null=True)),
                ('link_resultados', models.CharField(blank=True, max_length=300)),
                ('guia_envio', models.CharField(blank=True, max_length=50)),
                ('pagado', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2)),
                ('formato_ingreso_muestra', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2)),
                ('estatus', models.CharField(blank=True, choices=[('Invisible', 'Invisible'), ('Fantasma', 'Fantasma'), ('Creada', 'Creada'), ('Enviada', 'Enviada'), ('En laboratorio', 'En laboratorio'), ('Resultados', 'Resultados'), ('Borrado', 'Borrado')], max_length=15)),
                ('idioma_reporte', models.CharField(blank=True, choices=[('Español', 'Español'), ('Inglés', 'Inglés')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.Paquete')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cuentas.IFCUsuario')),
            ],
            options={
                'verbose_name': 'Orden Interna',
                'verbose_name_plural': 'Órdenes Internas',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='reportes.Analisis')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id_muestra', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=50)),
                ('variedad', models.CharField(max_length=50)),
                ('pais_origen', models.CharField(max_length=50)),
                ('codigo_muestra', models.CharField(max_length=50)),
                ('mrl', models.CharField(blank=True, max_length=200)),
                ('ubicacion', models.CharField(max_length=75)),
                ('estado', models.CharField(max_length=20)),
                ('parcela', models.CharField(max_length=50)),
                ('fecha_muestreo', models.DateField()),
                ('destino', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=20)),
                ('estado_muestra', models.BooleanField()),
                ('num_interno_informe', models.CharField(blank=True, max_length=50, null=True)),
                ('fechah_recibo', models.DateTimeField(blank=True, null=True)),
                ('fecha_eri', models.DateTimeField(blank=True, null=True)),
                ('muestreador', models.CharField(max_length=50)),
                ('fecha_forma', models.DateField()),
                ('orden_compra', models.CharField(blank=True, max_length=50, null=True)),
                ('enviado', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Factura')),
                ('oi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.OrdenInterna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.IFCUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('envio', models.DecimalField(decimal_places=2, max_digits=100)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('status', models.BooleanField(default=True)),
                ('aceptado', models.BooleanField(default=False)),
                ('fecha_creada', models.DateField(default=django.utils.timezone.now)),
                ('usuario_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='cuentas.IFCUsuario')),
                ('usuario_v', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='cuentas.IFCUsuario')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='AnalisisMuestra',
            fields=[
                ('id_analisis_muestra', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
                ('fecha', models.DateField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Analisis')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Muestra')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisCotizacion',
            fields=[
                ('id_analisis_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('descuento', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('iva', models.DecimalField(decimal_places=2, default=16, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Analisis')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Cotizacion')),
            ],
            options={
                'verbose_name': 'Analisis Cotizacion',
                'verbose_name_plural': 'Analisis Cotizaciones',
            },
        ),
        migrations.AddField(
            model_name='analisis',
            name='pais',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='reportes.Pais'),
        ),
    ]
