# Generated by Django 2.2.5 on 2019-10-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='tiempo',
            field=models.CharField(max_length=15),
        ),
    ]
