# Generated by Django 2.2.5 on 2019-10-17 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name': 'Orden Interna', 'verbose_name_plural': 'Órdenes Internas'},
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_creada',
            field=models.DateField(default=datetime.date(2019, 10, 17)),
        ),
    ]
