# Generated by Django 2.2.5 on 2019-10-10 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeninterna',
            name='estatus',
            field=models.CharField(blank=True, choices=[('invisible', 'invisible'), ('fantasma', 'fantasma'), ('activo', 'activo')], max_length=15),
        ),
        migrations.CreateModel(
            name='AnalisisMuestra',
            fields=[
                ('id_analisis_muestra', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
                ('fecha', models.DateField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Analisis')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.Muestra')),
            ],
        ),
    ]
