# Generated by Django 2.2.5 on 2019-10-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20191010_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='codigo_interno',
        ),
    ]
