# Generated by Django 2.2.5 on 2019-10-11 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20191010_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='codigo_interno',
        ),
        migrations.AddField(
            model_name='muestra',
            name='fecha_forma',
            field=models.DateField(default=datetime.date(2019, 10, 11)),
            preserve_default=False,
        ),
    ]
