# Generated by Django 2.2.5 on 2019-10-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_remove_muestra_codigo_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeninterna',
            name='idioma_reporte',
            field=models.CharField(blank=True, choices=[('8809 ES', '8809 ES'), ('8992 EN', '8992 EN')], max_length=20),
        ),
    ]
