# Generated by Django 2.2.5 on 2019-10-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_auto_20191011_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordeninterna',
            name='fecha_muestreo',
        ),
        migrations.RemoveField(
            model_name='ordeninterna',
            name='fechah_recibo',
        ),
        migrations.AddField(
            model_name='muestra',
            name='fechah_recibo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
