# Generated by Django 2.2.5 on 2019-10-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_usuarios', '0001_initial'),
        ('reportes', '0005_ordeninterna_fecha_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordeninterna',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_usuarios.IFCUsuario'),
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id_muestra', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=50)),
                ('variedad', models.CharField(max_length=50)),
                ('pais_origen', models.CharField(max_length=50)),
                ('codigo_muestra', models.CharField(max_length=50)),
                ('codigo_interno', models.CharField(max_length=50)),
                ('agricultor', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=75)),
                ('estado', models.CharField(max_length=20)),
                ('parcela', models.CharField(max_length=50)),
                ('fecha_muestreo', models.DateField()),
                ('destino', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=20)),
                ('estado_muestra', models.BooleanField()),
                ('oi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesamiento_reportes.OrdenInterna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_usuarios.IFCUsuario')),
            ],
        ),
    ]
