# Generated by Django 2.2.5 on 2019-10-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_auto_20191009_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordeninterna',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
