# Generated by Django 2.2.5 on 2019-10-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento_reportes', '0008_auto_20191009_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=30)),
                ('tiempo', models.IntegerField()),
            ],
        ),
    ]
