# Generated by Django 2.2.5 on 2019-10-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_usuarios', '0001_initial'),
        ('reportes', '0009_analisis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('descuento', models.DecimalField(decimal_places=4, max_digits=100)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=100)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('status', models.BooleanField()),
                ('usuario_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='admin_usuarios.IFCUsuario')),
                ('usuario_v', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='admin_usuarios.IFCUsuario')),
            ],
        ),
    ]
