# Generated by Django 2.2.5 on 2019-10-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20191014_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ifcusuario',
            options={'verbose_name': 'Usuario IFC', 'verbose_name_plural': 'Usuarios IFC'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
    ]
